# Generated by Django 5.2.14 on 2026-05-30 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateRiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField(default=dict)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=10)),
                ('season', models.CharField(max_length=20)),
                ('layer_type', models.CharField(default='climate_risk', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VegetationObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ndvi', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('lai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('soil_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lst', models.DecimalField(blank=True, decimal_places=2, help_text='Land Surface Temp °C', max_digits=5, null=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_observations', to='farms.farm')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.field')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StressAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetation_stress', models.DecimalField(decimal_places=1, max_digits=4)),
                ('heat_stress', models.DecimalField(decimal_places=1, max_digits=4)),
                ('water_stress', models.DecimalField(decimal_places=1, max_digits=4)),
                ('climate_stress', models.DecimalField(decimal_places=1, max_digits=4)),
                ('resilience_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_assessments', to='farms.farm')),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='climate.vegetationobservation')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=100)),
                ('scenario', models.CharField(choices=[('ssp245', 'SSP2-4.5'), ('ssp370', 'SSP3-7.0'), ('ssp585', 'SSP5-8.5')], max_length=10)),
                ('decade', models.IntegerField(choices=[(2030, '2030'), (2035, '2035'), (2040, '2040')])),
                ('rainfall_change_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('heat_stress_index', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dry_days_change', models.DecimalField(decimal_places=1, max_digits=5)),
                ('soil_moisture_trend', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water_stress_trend', models.DecimalField(decimal_places=1, max_digits=4)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='climate_projections', to='farms.farm')),
            ],
            options={
                'unique_together': {('farm', 'scenario', 'decade')},
            },
        ),
        migrations.CreateModel(
            name='LocationClimateIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('rainfall_outlook_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water_stress_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('heat_stress_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('agri_resilience_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('climate_stress_index', models.DecimalField(decimal_places=1, max_digits=4)),
                ('climate_risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], max_length=10)),
                ('rainfall_confidence', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('water_stress_confidence', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('heat_stress_confidence', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('agri_resilience_confidence', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('csi_confidence', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='climate_indices', to='farms.farm')),
            ],
            options={
                'unique_together': {('farm', 'season', 'year')},
            },
        ),
    ]
