# Generated by Django 5.2.14 on 2026-05-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('scenario', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('key_insight_1', models.TextField(blank=True, null=True)),
                ('key_insight_2', models.TextField(blank=True, null=True)),
                ('key_insight_3', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('district', 'scenario', 'year')},
            },
        ),
    ]
