# Generated by Django 5.2.14 on 2026-05-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0002_districtinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='climateriskzone',
            name='scenario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='climateriskzone',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='climateriskzone',
            name='risk_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='climateriskzone',
            name='season',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
