# Generated by Django 5.2.14 on 2026-05-30 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or URL', max_length=100, null=True)),
                ('category', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('water_requirement_mm', models.IntegerField(help_text='Typical water requirement in mm')),
                ('temp_min', models.FloatField(help_text='Minimum optimal temperature')),
                ('temp_max', models.FloatField(help_text='Maximum optimal temperature')),
                ('optimal_soil_moisture', models.FloatField(help_text='Optimal soil moisture percentage')),
            ],
        ),
        migrations.CreateModel(
            name='BestPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_practices', to='cropdata.crop')),
            ],
        ),
        migrations.CreateModel(
            name='CropCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agro_zone', models.CharField(max_length=100)),
                ('sowing_start', models.DateField()),
                ('sowing_end', models.DateField()),
                ('vegetative', models.IntegerField(help_text='Days for vegetative stage')),
                ('flowering', models.IntegerField(help_text='Days for flowering stage')),
                ('harvest', models.IntegerField(help_text='Days for harvest stage')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='cropdata.crop')),
            ],
        ),
    ]
