# Generated by Django 5.2.14 on 2026-05-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSuitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=100)),
                ('suitability_current', models.CharField(blank=True, max_length=50, null=True)),
                ('suitability_projected', models.CharField(blank=True, max_length=50, null=True)),
                ('change_class', models.IntegerField(default=0)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Crop Suitabilities',
            },
        ),
    ]
