# Generated by Django 5.2.14 on 2026-05-30 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cropdata', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('recommended_cycles', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True)),
                ('next_activity', models.CharField(blank=True, max_length=200)),
                ('window', models.CharField(blank=True, help_text='e.g. Jun 15 – Jun 22', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_advisories', to='farms.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YieldRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('risk_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_label', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('yield_low_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yield_high_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cropdata.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_risks', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='CropSuitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('suitability_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommendation_label', models.CharField(max_length=50)),
                ('expected_yield_min', models.DecimalField(decimal_places=2, help_text='q/ha', max_digits=8)),
                ('expected_yield_max', models.DecimalField(decimal_places=2, help_text='q/ha', max_digits=8)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('reasons', models.JSONField(default=list, help_text='List of reason strings')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitability_records', to='cropdata.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_suitabilities', to='farms.farm')),
            ],
            options={
                'unique_together': {('crop', 'farm', 'season', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CropSuitabilityTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('suitability_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitability_trends', to='cropdata.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_suitability_trends', to='farms.farm')),
            ],
            options={
                'unique_together': {('crop', 'farm', 'scenario', 'year')},
            },
        ),
        migrations.CreateModel(
            name='WaterBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('month', models.PositiveSmallIntegerField()),
                ('requirement_mm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('availability_mm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_balances', to='farms.farm')),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('farm', 'season', 'month')},
            },
        ),
    ]
